# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtraffic_dialog_base.ui'
#
# Created: Tue Sep  8 18:24:05 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_qtraffic_dockWidget(object):
    def setupUi(self, qtraffic_dockWidget):
        qtraffic_dockWidget.setObjectName(_fromUtf8("qtraffic_dockWidget"))
        qtraffic_dockWidget.resize(790, 521)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qtraffic_dockWidget.setWindowIcon(icon)
        qtraffic_dockWidget.setFloating(False)
        self.qtraffic_widget = QtGui.QWidget()
        self.qtraffic_widget.setObjectName(_fromUtf8("qtraffic_widget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.qtraffic_widget)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.tabWidget = QtGui.QTabWidget(self.qtraffic_widget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.project_tab = QtGui.QWidget()
        self.project_tab.setObjectName(_fromUtf8("project_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.project_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label = QtGui.QLabel(self.project_tab)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_21.addWidget(self.label)
        self.projectName_lineEdit = QtGui.QLineEdit(self.project_tab)
        self.projectName_lineEdit.setObjectName(_fromUtf8("projectName_lineEdit"))
        self.horizontalLayout_21.addWidget(self.projectName_lineEdit)
        self.selectProject_TButton = QtGui.QToolButton(self.project_tab)
        self.selectProject_TButton.setObjectName(_fromUtf8("selectProject_TButton"))
        self.horizontalLayout_21.addWidget(self.selectProject_TButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.newProject_PButton = QtGui.QPushButton(self.project_tab)
        self.newProject_PButton.setObjectName(_fromUtf8("newProject_PButton"))
        self.horizontalLayout_23.addWidget(self.newProject_PButton)
        self.saveAsProject_PButton = QtGui.QPushButton(self.project_tab)
        self.saveAsProject_PButton.setObjectName(_fromUtf8("saveAsProject_PButton"))
        self.horizontalLayout_23.addWidget(self.saveAsProject_PButton)
        self.saveProject_PButton = QtGui.QPushButton(self.project_tab)
        self.saveProject_PButton.setObjectName(_fromUtf8("saveProject_PButton"))
        self.horizontalLayout_23.addWidget(self.saveProject_PButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.tabWidget.addTab(self.project_tab, _fromUtf8(""))
        self.input_tab = QtGui.QWidget()
        self.input_tab.setObjectName(_fromUtf8("input_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.input_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.input_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.inputLayer_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.inputLayer_lineEdit.setObjectName(_fromUtf8("inputLayer_lineEdit"))
        self.horizontalLayout.addWidget(self.inputLayer_lineEdit)
        self.selectLayer_TButton = QtGui.QToolButton(self.groupBox)
        self.selectLayer_TButton.setObjectName(_fromUtf8("selectLayer_TButton"))
        self.horizontalLayout.addWidget(self.selectLayer_TButton)
        self.selectFile_TButton = QtGui.QToolButton(self.groupBox)
        self.selectFile_TButton.setObjectName(_fromUtf8("selectFile_TButton"))
        self.horizontalLayout.addWidget(self.selectFile_TButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.input_tab)
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.roadType_CBox = QtGui.QComboBox(self.groupBox_2)
        self.roadType_CBox.setObjectName(_fromUtf8("roadType_CBox"))
        self.verticalLayout_7.addWidget(self.roadType_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_14.addWidget(self.label_8)
        self.averageVehicleSpeed_Cbox = QtGui.QComboBox(self.groupBox_2)
        self.averageVehicleSpeed_Cbox.setObjectName(_fromUtf8("averageVehicleSpeed_Cbox"))
        self.verticalLayout_14.addWidget(self.averageVehicleSpeed_Cbox)
        self.gridLayout_3.addLayout(self.verticalLayout_14, 4, 0, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_13.addWidget(self.label_7)
        self.passengerCarsCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.passengerCarsCount_CBox.setObjectName(_fromUtf8("passengerCarsCount_CBox"))
        self.verticalLayout_13.addWidget(self.passengerCarsCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_13, 1, 1, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.roadLenght_CBox = QtGui.QComboBox(self.groupBox_2)
        self.roadLenght_CBox.setObjectName(_fromUtf8("roadLenght_CBox"))
        self.verticalLayout_10.addWidget(self.roadLenght_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_19.addWidget(self.label_13)
        self.urbanBusesCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.urbanBusesCount_CBox.setObjectName(_fromUtf8("urbanBusesCount_CBox"))
        self.verticalLayout_19.addWidget(self.urbanBusesCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_19, 1, 2, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.roadGradient_CBox = QtGui.QComboBox(self.groupBox_2)
        self.roadGradient_CBox.setObjectName(_fromUtf8("roadGradient_CBox"))
        self.verticalLayout_11.addWidget(self.roadGradient_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 3, 0, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_15.addWidget(self.label_9)
        self.lightDutyVehicleCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.lightDutyVehicleCount_CBox.setObjectName(_fromUtf8("lightDutyVehicleCount_CBox"))
        self.verticalLayout_15.addWidget(self.lightDutyVehicleCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_15, 2, 1, 1, 1)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_18.addWidget(self.label_11)
        self.heavyDutyVehicleCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.heavyDutyVehicleCount_CBox.setObjectName(_fromUtf8("heavyDutyVehicleCount_CBox"))
        self.verticalLayout_18.addWidget(self.heavyDutyVehicleCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_18, 3, 1, 1, 1)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_20.addWidget(self.label_15)
        self.coachesCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.coachesCount_CBox.setObjectName(_fromUtf8("coachesCount_CBox"))
        self.verticalLayout_20.addWidget(self.coachesCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_20, 2, 2, 1, 1)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_23.addWidget(self.label_17)
        self.motorcycleCount_CBox = QtGui.QComboBox(self.groupBox_2)
        self.motorcycleCount_CBox.setObjectName(_fromUtf8("motorcycleCount_CBox"))
        self.verticalLayout_23.addWidget(self.motorcycleCount_CBox)
        self.gridLayout_3.addLayout(self.verticalLayout_23, 3, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.inputNetwork_validate_PButton = QtGui.QPushButton(self.input_tab)
        self.inputNetwork_validate_PButton.setObjectName(_fromUtf8("inputNetwork_validate_PButton"))
        self.horizontalLayout_2.addWidget(self.inputNetwork_validate_PButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.input_tab, _fromUtf8(""))
        self.fleetComposition_tab = QtGui.QWidget()
        self.fleetComposition_tab.setObjectName(_fromUtf8("fleetComposition_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fleetComposition_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.newRoadType_button = QtGui.QPushButton(self.fleetComposition_tab)
        self.newRoadType_button.setObjectName(_fromUtf8("newRoadType_button"))
        self.verticalLayout_12.addWidget(self.newRoadType_button)
        self.removeRoadType_button = QtGui.QPushButton(self.fleetComposition_tab)
        self.removeRoadType_button.setObjectName(_fromUtf8("removeRoadType_button"))
        self.verticalLayout_12.addWidget(self.removeRoadType_button)
        self.roadTypes_listWidget = QtGui.QListWidget(self.fleetComposition_tab)
        self.roadTypes_listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.roadTypes_listWidget.setObjectName(_fromUtf8("roadTypes_listWidget"))
        self.verticalLayout_12.addWidget(self.roadTypes_listWidget)
        self.loadDefaultConfiguration_button = QtGui.QPushButton(self.fleetComposition_tab)
        self.loadDefaultConfiguration_button.setObjectName(_fromUtf8("loadDefaultConfiguration_button"))
        self.verticalLayout_12.addWidget(self.loadDefaultConfiguration_button)
        self.loadConfiguration_button = QtGui.QPushButton(self.fleetComposition_tab)
        self.loadConfiguration_button.setObjectName(_fromUtf8("loadConfiguration_button"))
        self.verticalLayout_12.addWidget(self.loadConfiguration_button)
        self.saveConfiguration_button = QtGui.QPushButton(self.fleetComposition_tab)
        self.saveConfiguration_button.setObjectName(_fromUtf8("saveConfiguration_button"))
        self.verticalLayout_12.addWidget(self.saveConfiguration_button)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.fleetComposition_tabs = QtGui.QTabWidget(self.fleetComposition_tab)
        self.fleetComposition_tabs.setObjectName(_fromUtf8("fleetComposition_tabs"))
        self.passengerCars_tab = QtGui.QWidget()
        self.passengerCars_tab.setObjectName(_fromUtf8("passengerCars_tab"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.passengerCars_tab)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.passengerCars_webView = QtWebKit.QWebView(self.passengerCars_tab)
        self.passengerCars_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.passengerCars_webView.setObjectName(_fromUtf8("passengerCars_webView"))
        self.horizontalLayout_7.addWidget(self.passengerCars_webView)
        self.fleetComposition_tabs.addTab(self.passengerCars_tab, _fromUtf8(""))
        self.lightDutyVehicles_tab = QtGui.QWidget()
        self.lightDutyVehicles_tab.setObjectName(_fromUtf8("lightDutyVehicles_tab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.lightDutyVehicles_tab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lightDutyVehicles_webView = QtWebKit.QWebView(self.lightDutyVehicles_tab)
        self.lightDutyVehicles_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.lightDutyVehicles_webView.setObjectName(_fromUtf8("lightDutyVehicles_webView"))
        self.horizontalLayout_8.addWidget(self.lightDutyVehicles_webView)
        self.fleetComposition_tabs.addTab(self.lightDutyVehicles_tab, _fromUtf8(""))
        self.heavyDutyVehicles_tab = QtGui.QWidget()
        self.heavyDutyVehicles_tab.setObjectName(_fromUtf8("heavyDutyVehicles_tab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.heavyDutyVehicles_tab)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.heavyDutyVehicles_webView = QtWebKit.QWebView(self.heavyDutyVehicles_tab)
        self.heavyDutyVehicles_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.heavyDutyVehicles_webView.setObjectName(_fromUtf8("heavyDutyVehicles_webView"))
        self.horizontalLayout_9.addWidget(self.heavyDutyVehicles_webView)
        self.fleetComposition_tabs.addTab(self.heavyDutyVehicles_tab, _fromUtf8(""))
        self.urbanBuses_tab = QtGui.QWidget()
        self.urbanBuses_tab.setObjectName(_fromUtf8("urbanBuses_tab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.urbanBuses_tab)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.buses_webView = QtWebKit.QWebView(self.urbanBuses_tab)
        self.buses_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.buses_webView.setObjectName(_fromUtf8("buses_webView"))
        self.horizontalLayout_10.addWidget(self.buses_webView)
        self.fleetComposition_tabs.addTab(self.urbanBuses_tab, _fromUtf8(""))
        self.coaches_tab = QtGui.QWidget()
        self.coaches_tab.setObjectName(_fromUtf8("coaches_tab"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.coaches_tab)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.coaches_webView = QtWebKit.QWebView(self.coaches_tab)
        self.coaches_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.coaches_webView.setObjectName(_fromUtf8("coaches_webView"))
        self.horizontalLayout_12.addWidget(self.coaches_webView)
        self.fleetComposition_tabs.addTab(self.coaches_tab, _fromUtf8(""))
        self.motorcycles_tab = QtGui.QWidget()
        self.motorcycles_tab.setObjectName(_fromUtf8("motorcycles_tab"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.motorcycles_tab)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.motors_webView = QtWebKit.QWebView(self.motorcycles_tab)
        self.motors_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.motors_webView.setObjectName(_fromUtf8("motors_webView"))
        self.horizontalLayout_11.addWidget(self.motors_webView)
        self.fleetComposition_tabs.addTab(self.motorcycles_tab, _fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.fleetComposition_tabs)
        self.horizontalLayout_14.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        spacerItem4 = QtGui.QSpacerItem(20, 105, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.fleetComposition_tab, _fromUtf8(""))
        self.parameters_tab = QtGui.QWidget()
        self.parameters_tab.setObjectName(_fromUtf8("parameters_tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.parameters_tab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.groupBox_6 = QtGui.QGroupBox(self.parameters_tab)
        self.groupBox_6.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.gasolineSulphureContent_SBox = QtGui.QSpinBox(self.groupBox_6)
        self.gasolineSulphureContent_SBox.setMaximum(999999999)
        self.gasolineSulphureContent_SBox.setObjectName(_fromUtf8("gasolineSulphureContent_SBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.gasolineSulphureContent_SBox)
        self.horizontalLayout_15.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.parameters_tab)
        self.groupBox_7.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.dieselSulphureContent_SBox = QtGui.QSpinBox(self.groupBox_7)
        self.dieselSulphureContent_SBox.setMaximum(999999999)
        self.dieselSulphureContent_SBox.setObjectName(_fromUtf8("dieselSulphureContent_SBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dieselSulphureContent_SBox)
        self.horizontalLayout_15.addWidget(self.groupBox_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.openFunctionEditor_PButton = QtGui.QPushButton(self.parameters_tab)
        self.openFunctionEditor_PButton.setObjectName(_fromUtf8("openFunctionEditor_PButton"))
        self.verticalLayout_9.addWidget(self.openFunctionEditor_PButton)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.parameters_loadDefault_PButton = QtGui.QPushButton(self.parameters_tab)
        self.parameters_loadDefault_PButton.setObjectName(_fromUtf8("parameters_loadDefault_PButton"))
        self.horizontalLayout_13.addWidget(self.parameters_loadDefault_PButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.parameters_tab, _fromUtf8(""))
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName(_fromUtf8("output_tab"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.output_tab)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.groupBox_3 = QtGui.QGroupBox(self.output_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.createNewLayer_RButton = QtGui.QRadioButton(self.groupBox_3)
        self.createNewLayer_RButton.setObjectName(_fromUtf8("createNewLayer_RButton"))
        self.outFileLayer_BGroup = QtGui.QButtonGroup(qtraffic_dockWidget)
        self.outFileLayer_BGroup.setObjectName(_fromUtf8("outFileLayer_BGroup"))
        self.outFileLayer_BGroup.addButton(self.createNewLayer_RButton)
        self.gridLayout_6.addWidget(self.createNewLayer_RButton, 2, 0, 1, 1)
        self.addToOriginaLayer_RButton = QtGui.QRadioButton(self.groupBox_3)
        self.addToOriginaLayer_RButton.setObjectName(_fromUtf8("addToOriginaLayer_RButton"))
        self.outFileLayer_BGroup.addButton(self.addToOriginaLayer_RButton)
        self.gridLayout_6.addWidget(self.addToOriginaLayer_RButton, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outFile_LEdit = QtGui.QLineEdit(self.groupBox_3)
        self.outFile_LEdit.setObjectName(_fromUtf8("outFile_LEdit"))
        self.horizontalLayout_4.addWidget(self.outFile_LEdit)
        self.selectOutfile_TButton = QtGui.QToolButton(self.groupBox_3)
        self.selectOutfile_TButton.setObjectName(_fromUtf8("selectOutfile_TButton"))
        self.horizontalLayout_4.addWidget(self.selectOutfile_TButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.groupBox_3)
        self.groupBox_9 = QtGui.QGroupBox(self.output_tab)
        self.groupBox_9.setStyleSheet(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.fuelEnergyConsumptionGasoline_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.fuelEnergyConsumptionGasoline_CBox.setObjectName(_fromUtf8("fuelEnergyConsumptionGasoline_CBox"))
        self.gridLayout_4.addWidget(self.fuelEnergyConsumptionGasoline_CBox, 0, 0, 1, 1)
        self.fuelEnergyConsumptionLPG_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.fuelEnergyConsumptionLPG_CBox.setObjectName(_fromUtf8("fuelEnergyConsumptionLPG_CBox"))
        self.gridLayout_4.addWidget(self.fuelEnergyConsumptionLPG_CBox, 0, 1, 1, 1)
        self.totalFuelConsumption_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.totalFuelConsumption_CBox.setObjectName(_fromUtf8("totalFuelConsumption_CBox"))
        self.gridLayout_4.addWidget(self.totalFuelConsumption_CBox, 0, 2, 1, 1)
        self.fuelEnergyConsumptionDiesel_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.fuelEnergyConsumptionDiesel_CBox.setObjectName(_fromUtf8("fuelEnergyConsumptionDiesel_CBox"))
        self.gridLayout_4.addWidget(self.fuelEnergyConsumptionDiesel_CBox, 1, 0, 1, 1)
        self.fuelEnergyConsumptionNewFuels_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.fuelEnergyConsumptionNewFuels_CBox.setObjectName(_fromUtf8("fuelEnergyConsumptionNewFuels_CBox"))
        self.gridLayout_4.addWidget(self.fuelEnergyConsumptionNewFuels_CBox, 1, 1, 1, 1)
        self.energyConsumption_CBox = QtGui.QCheckBox(self.groupBox_9)
        self.energyConsumption_CBox.setObjectName(_fromUtf8("energyConsumption_CBox"))
        self.gridLayout_4.addWidget(self.energyConsumption_CBox, 1, 2, 1, 1)
        self.verticalLayout_17.addWidget(self.groupBox_9)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.groupBox_4 = QtGui.QGroupBox(self.output_tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_10.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.pollutantsCO2_CBox = QtGui.QCheckBox(self.groupBox_10)
        self.pollutantsCO2_CBox.setObjectName(_fromUtf8("pollutantsCO2_CBox"))
        self.verticalLayout_21.addWidget(self.pollutantsCO2_CBox)
        self.pollutantsCH4_CBox = QtGui.QCheckBox(self.groupBox_10)
        self.pollutantsCH4_CBox.setObjectName(_fromUtf8("pollutantsCH4_CBox"))
        self.verticalLayout_21.addWidget(self.pollutantsCH4_CBox)
        self.pollutantsN2O_CBox = QtGui.QCheckBox(self.groupBox_10)
        self.pollutantsN2O_CBox.setObjectName(_fromUtf8("pollutantsN2O_CBox"))
        self.verticalLayout_21.addWidget(self.pollutantsN2O_CBox)
        self.gridLayout_2.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_12.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.pollutantsPM25_CBox = QtGui.QCheckBox(self.groupBox_12)
        self.pollutantsPM25_CBox.setObjectName(_fromUtf8("pollutantsPM25_CBox"))
        self.verticalLayout_24.addWidget(self.pollutantsPM25_CBox)
        self.gridLayout_2.addWidget(self.groupBox_12, 1, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_8.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pollutantsCO_CBox = QtGui.QCheckBox(self.groupBox_8)
        self.pollutantsCO_CBox.setObjectName(_fromUtf8("pollutantsCO_CBox"))
        self.verticalLayout_6.addWidget(self.pollutantsCO_CBox)
        self.pollutantsNOx_CBox = QtGui.QCheckBox(self.groupBox_8)
        self.pollutantsNOx_CBox.setObjectName(_fromUtf8("pollutantsNOx_CBox"))
        self.verticalLayout_6.addWidget(self.pollutantsNOx_CBox)
        self.pollutantsNMVOCs_CBox = QtGui.QCheckBox(self.groupBox_8)
        self.pollutantsNMVOCs_CBox.setObjectName(_fromUtf8("pollutantsNMVOCs_CBox"))
        self.verticalLayout_6.addWidget(self.pollutantsNMVOCs_CBox)
        self.gridLayout_2.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_11.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.pollutantsNH3_CBox = QtGui.QCheckBox(self.groupBox_11)
        self.pollutantsNH3_CBox.setObjectName(_fromUtf8("pollutantsNH3_CBox"))
        self.verticalLayout_22.addWidget(self.pollutantsNH3_CBox)
        self.pollutantsSO2_CBox = QtGui.QCheckBox(self.groupBox_11)
        self.pollutantsSO2_CBox.setObjectName(_fromUtf8("pollutantsSO2_CBox"))
        self.verticalLayout_22.addWidget(self.pollutantsSO2_CBox)
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 2, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_13.setStyleSheet(_fromUtf8("QGroupBox{\n"
"    border:1px solid gray;\n"
"    border-radius:5px;\n"
"    margin-top: 1ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position:top center;\n"
"    padding:0 3px;\n"
"}"))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.pollutantsC6H6_CBox = QtGui.QCheckBox(self.groupBox_13)
        self.pollutantsC6H6_CBox.setObjectName(_fromUtf8("pollutantsC6H6_CBox"))
        self.verticalLayout_25.addWidget(self.pollutantsC6H6_CBox)
        self.gridLayout_2.addWidget(self.groupBox_13, 1, 1, 1, 1)
        self.horizontalLayout_20.addWidget(self.groupBox_4)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.calculate_PButton = QtGui.QPushButton(self.output_tab)
        self.calculate_PButton.setObjectName(_fromUtf8("calculate_PButton"))
        self.horizontalLayout_3.addWidget(self.calculate_PButton)
        self.verticalLayout_17.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.output_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.webView = QtWebKit.QWebView(self.tab)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_5.addWidget(self.webView)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.tabWidget)
        qtraffic_dockWidget.setWidget(self.qtraffic_widget)

        self.retranslateUi(qtraffic_dockWidget)
        self.tabWidget.setCurrentIndex(0)
        self.fleetComposition_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(qtraffic_dockWidget)

    def retranslateUi(self, qtraffic_dockWidget):
        qtraffic_dockWidget.setWindowTitle(_translate("qtraffic_dockWidget", "QTraffic", None))
        self.label.setText(_translate("qtraffic_dockWidget", "Current Project", None))
        self.selectProject_TButton.setText(_translate("qtraffic_dockWidget", "...", None))
        self.newProject_PButton.setText(_translate("qtraffic_dockWidget", "New", None))
        self.saveAsProject_PButton.setText(_translate("qtraffic_dockWidget", "Save As", None))
        self.saveProject_PButton.setText(_translate("qtraffic_dockWidget", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.project_tab), _translate("qtraffic_dockWidget", "Project", None))
        self.groupBox.setTitle(_translate("qtraffic_dockWidget", "Input Layer", None))
        self.selectLayer_TButton.setText(_translate("qtraffic_dockWidget", "From Layer", None))
        self.selectFile_TButton.setText(_translate("qtraffic_dockWidget", "From Shape", None))
        self.groupBox_2.setTitle(_translate("qtraffic_dockWidget", "Table Column Select", None))
        self.label_2.setText(_translate("qtraffic_dockWidget", "Road type (link to fleet composition)", None))
        self.label_8.setText(_translate("qtraffic_dockWidget", "Average vehicle speed (km/h)", None))
        self.label_7.setText(_translate("qtraffic_dockWidget", "Passenger cars count", None))
        self.label_5.setText(_translate("qtraffic_dockWidget", "Road Lenght (meters)", None))
        self.label_13.setText(_translate("qtraffic_dockWidget", "Urban buses count", None))
        self.label_6.setText(_translate("qtraffic_dockWidget", "Road Gradient", None))
        self.label_9.setText(_translate("qtraffic_dockWidget", "Light duty vehicles count", None))
        self.label_11.setText(_translate("qtraffic_dockWidget", "Heavy duty vehicles count", None))
        self.label_15.setText(_translate("qtraffic_dockWidget", "Coaches count", None))
        self.label_17.setText(_translate("qtraffic_dockWidget", "Motorcycles count", None))
        self.inputNetwork_validate_PButton.setText(_translate("qtraffic_dockWidget", "Validate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_tab), _translate("qtraffic_dockWidget", "Input Network", None))
        self.newRoadType_button.setText(_translate("qtraffic_dockWidget", "Add road type", None))
        self.removeRoadType_button.setText(_translate("qtraffic_dockWidget", "Remove road type", None))
        self.roadTypes_listWidget.setSortingEnabled(True)
        self.loadDefaultConfiguration_button.setText(_translate("qtraffic_dockWidget", "Load Defaults", None))
        self.loadConfiguration_button.setText(_translate("qtraffic_dockWidget", "Load", None))
        self.saveConfiguration_button.setText(_translate("qtraffic_dockWidget", "Save", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.passengerCars_tab), _translate("qtraffic_dockWidget", "Passenger cars", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.lightDutyVehicles_tab), _translate("qtraffic_dockWidget", "Light duty vehicles", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.heavyDutyVehicles_tab), _translate("qtraffic_dockWidget", "Heavy duty vehicles", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.urbanBuses_tab), _translate("qtraffic_dockWidget", "Urban buses", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.coaches_tab), _translate("qtraffic_dockWidget", "Coaches", None))
        self.fleetComposition_tabs.setTabText(self.fleetComposition_tabs.indexOf(self.motorcycles_tab), _translate("qtraffic_dockWidget", "Motorcycles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fleetComposition_tab), _translate("qtraffic_dockWidget", "Fleet Composition", None))
        self.groupBox_6.setTitle(_translate("qtraffic_dockWidget", "Gasoline properties", None))
        self.label_3.setText(_translate("qtraffic_dockWidget", "Sulphure contents (ppm)", None))
        self.groupBox_7.setTitle(_translate("qtraffic_dockWidget", "Diesel properties", None))
        self.label_12.setText(_translate("qtraffic_dockWidget", "Sulphure contents (ppm)", None))
        self.openFunctionEditor_PButton.setText(_translate("qtraffic_dockWidget", "Define emission factors for new fuel", None))
        self.parameters_loadDefault_PButton.setText(_translate("qtraffic_dockWidget", "Load default", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parameters_tab), _translate("qtraffic_dockWidget", "Fuel properties", None))
        self.groupBox_3.setTitle(_translate("qtraffic_dockWidget", "Output File", None))
        self.createNewLayer_RButton.setText(_translate("qtraffic_dockWidget", "Create new layer", None))
        self.addToOriginaLayer_RButton.setText(_translate("qtraffic_dockWidget", "Add to the original layer", None))
        self.selectOutfile_TButton.setText(_translate("qtraffic_dockWidget", "...", None))
        self.groupBox_9.setTitle(_translate("qtraffic_dockWidget", "Fuel (g/km) and Energy (MJ/km) consumption", None))
        self.fuelEnergyConsumptionGasoline_CBox.setText(_translate("qtraffic_dockWidget", "Gasoline", None))
        self.fuelEnergyConsumptionLPG_CBox.setText(_translate("qtraffic_dockWidget", "LPG", None))
        self.totalFuelConsumption_CBox.setText(_translate("qtraffic_dockWidget", "Total Fuel consumption", None))
        self.fuelEnergyConsumptionDiesel_CBox.setText(_translate("qtraffic_dockWidget", "Diesel", None))
        self.fuelEnergyConsumptionNewFuels_CBox.setText(_translate("qtraffic_dockWidget", "New fuels", None))
        self.energyConsumption_CBox.setText(_translate("qtraffic_dockWidget", "Energy", None))
        self.groupBox_4.setTitle(_translate("qtraffic_dockWidget", "Emissions (g/km)", None))
        self.groupBox_10.setTitle(_translate("qtraffic_dockWidget", "Greenhouse gases", None))
        self.pollutantsCO2_CBox.setText(_translate("qtraffic_dockWidget", "CO2", None))
        self.pollutantsCH4_CBox.setText(_translate("qtraffic_dockWidget", "CH4", None))
        self.pollutantsN2O_CBox.setText(_translate("qtraffic_dockWidget", "N2O", None))
        self.groupBox_12.setTitle(_translate("qtraffic_dockWidget", "Particulate Matter", None))
        self.pollutantsPM25_CBox.setText(_translate("qtraffic_dockWidget", "PM 2.5", None))
        self.groupBox_8.setTitle(_translate("qtraffic_dockWidget", "Ozone precursors", None))
        self.pollutantsCO_CBox.setText(_translate("qtraffic_dockWidget", "CO", None))
        self.pollutantsNOx_CBox.setText(_translate("qtraffic_dockWidget", "NOx", None))
        self.pollutantsNMVOCs_CBox.setText(_translate("qtraffic_dockWidget", "NMVOCs", None))
        self.groupBox_11.setTitle(_translate("qtraffic_dockWidget", "Acidifying substances", None))
        self.pollutantsNH3_CBox.setText(_translate("qtraffic_dockWidget", "NH3", None))
        self.pollutantsSO2_CBox.setText(_translate("qtraffic_dockWidget", "SO2", None))
        self.groupBox_13.setTitle(_translate("qtraffic_dockWidget", "Carcinogenic species", None))
        self.pollutantsC6H6_CBox.setText(_translate("qtraffic_dockWidget", "C6H6", None))
        self.calculate_PButton.setText(_translate("qtraffic_dockWidget", "Calculate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), _translate("qtraffic_dockWidget", "Output", None))
        self.pushButton_2.setText(_translate("qtraffic_dockWidget", "About", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("qtraffic_dockWidget", "Help", None))

from PyQt4 import QtWebKit
