# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtraffic_dialog_base.ui'
#
# Created: Sun May  3 11:39:05 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_qtraffic_dockWidget(object):
    def setupUi(self, qtraffic_dockWidget):
        qtraffic_dockWidget.setObjectName(_fromUtf8("qtraffic_dockWidget"))
        qtraffic_dockWidget.resize(1072, 405)
        qtraffic_dockWidget.setFloating(False)
        self.qtraffic_widget = QtGui.QWidget()
        self.qtraffic_widget.setObjectName(_fromUtf8("qtraffic_widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.qtraffic_widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.qtraffic_widget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.input_tab = QtGui.QWidget()
        self.input_tab.setObjectName(_fromUtf8("input_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.input_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.input_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.input_tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.linkId_combo = QtGui.QComboBox(self.groupBox_2)
        self.linkId_combo.setEditable(True)
        self.linkId_combo.setObjectName(_fromUtf8("linkId_combo"))
        self.verticalLayout_6.addWidget(self.linkId_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.vehicleCount_combo = QtGui.QComboBox(self.groupBox_2)
        self.vehicleCount_combo.setEditable(True)
        self.vehicleCount_combo.setObjectName(_fromUtf8("vehicleCount_combo"))
        self.verticalLayout_8.addWidget(self.vehicleCount_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.linkType_combo = QtGui.QComboBox(self.groupBox_2)
        self.linkType_combo.setEditable(True)
        self.linkType_combo.setObjectName(_fromUtf8("linkType_combo"))
        self.verticalLayout_7.addWidget(self.linkType_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_9.addWidget(self.label_4)
        self.vehicleSpeed_combo = QtGui.QComboBox(self.groupBox_2)
        self.vehicleSpeed_combo.setEditable(True)
        self.vehicleSpeed_combo.setObjectName(_fromUtf8("vehicleSpeed_combo"))
        self.verticalLayout_9.addWidget(self.vehicleSpeed_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.roadLenght_combo = QtGui.QComboBox(self.groupBox_2)
        self.roadLenght_combo.setEditable(True)
        self.roadLenght_combo.setObjectName(_fromUtf8("roadLenght_combo"))
        self.verticalLayout_10.addWidget(self.roadLenght_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 1, 1, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.roadGradient_combo = QtGui.QComboBox(self.groupBox_2)
        self.roadGradient_combo.setEditable(True)
        self.roadGradient_combo.setObjectName(_fromUtf8("roadGradient_combo"))
        self.verticalLayout_11.addWidget(self.roadGradient_combo)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.next_pushButton = QtGui.QPushButton(self.input_tab)
        self.next_pushButton.setObjectName(_fromUtf8("next_pushButton"))
        self.horizontalLayout_2.addWidget(self.next_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.input_tab, _fromUtf8(""))
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName(_fromUtf8("output_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.output_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.output_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtGui.QToolButton(self.groupBox_3)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_4.addWidget(self.toolButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.output_tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_2.addWidget(self.checkBox_6, 4, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_2.addWidget(self.checkBox_7, 4, 2, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_2.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_2.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.calculate_pushButton = QtGui.QPushButton(self.output_tab)
        self.calculate_pushButton.setObjectName(_fromUtf8("calculate_pushButton"))
        self.horizontalLayout_3.addWidget(self.calculate_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.output_tab, _fromUtf8(""))
        self.configuration_tab = QtGui.QWidget()
        self.configuration_tab.setObjectName(_fromUtf8("configuration_tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.configuration_tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.roadTypes_listWidget = QtGui.QListWidget(self.configuration_tab)
        self.roadTypes_listWidget.setObjectName(_fromUtf8("roadTypes_listWidget"))
        self.horizontalLayout_6.addWidget(self.roadTypes_listWidget)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.newRoadType_button = QtGui.QPushButton(self.configuration_tab)
        self.newRoadType_button.setObjectName(_fromUtf8("newRoadType_button"))
        self.verticalLayout_12.addWidget(self.newRoadType_button)
        self.removeRoadType_button = QtGui.QPushButton(self.configuration_tab)
        self.removeRoadType_button.setObjectName(_fromUtf8("removeRoadType_button"))
        self.verticalLayout_12.addWidget(self.removeRoadType_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.loadConfiguration_button = QtGui.QPushButton(self.configuration_tab)
        self.loadConfiguration_button.setObjectName(_fromUtf8("loadConfiguration_button"))
        self.verticalLayout_12.addWidget(self.loadConfiguration_button)
        self.saveConfiguration_button = QtGui.QPushButton(self.configuration_tab)
        self.saveConfiguration_button.setObjectName(_fromUtf8("saveConfiguration_button"))
        self.verticalLayout_12.addWidget(self.saveConfiguration_button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.configurations_tabs = QtGui.QTabWidget(self.configuration_tab)
        self.configurations_tabs.setObjectName(_fromUtf8("configurations_tabs"))
        self.passengerCars_tab = QtGui.QWidget()
        self.passengerCars_tab.setObjectName(_fromUtf8("passengerCars_tab"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.passengerCars_tab)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.passengerCars_webView = QtWebKit.QWebView(self.passengerCars_tab)
        self.passengerCars_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.passengerCars_webView.setObjectName(_fromUtf8("passengerCars_webView"))
        self.horizontalLayout_7.addWidget(self.passengerCars_webView)
        self.configurations_tabs.addTab(self.passengerCars_tab, _fromUtf8(""))
        self.lightDutyVehicles_tab = QtGui.QWidget()
        self.lightDutyVehicles_tab.setObjectName(_fromUtf8("lightDutyVehicles_tab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.lightDutyVehicles_tab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lightDutyVehicles_webView = QtWebKit.QWebView(self.lightDutyVehicles_tab)
        self.lightDutyVehicles_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.lightDutyVehicles_webView.setObjectName(_fromUtf8("lightDutyVehicles_webView"))
        self.horizontalLayout_8.addWidget(self.lightDutyVehicles_webView)
        self.configurations_tabs.addTab(self.lightDutyVehicles_tab, _fromUtf8(""))
        self.heavyDutyVehicles_tab = QtGui.QWidget()
        self.heavyDutyVehicles_tab.setObjectName(_fromUtf8("heavyDutyVehicles_tab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.heavyDutyVehicles_tab)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.heavyDutyVehicles_webView = QtWebKit.QWebView(self.heavyDutyVehicles_tab)
        self.heavyDutyVehicles_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.heavyDutyVehicles_webView.setObjectName(_fromUtf8("heavyDutyVehicles_webView"))
        self.horizontalLayout_9.addWidget(self.heavyDutyVehicles_webView)
        self.configurations_tabs.addTab(self.heavyDutyVehicles_tab, _fromUtf8(""))
        self.buses_tab = QtGui.QWidget()
        self.buses_tab.setObjectName(_fromUtf8("buses_tab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.buses_tab)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.buses_webView = QtWebKit.QWebView(self.buses_tab)
        self.buses_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.buses_webView.setObjectName(_fromUtf8("buses_webView"))
        self.horizontalLayout_10.addWidget(self.buses_webView)
        self.configurations_tabs.addTab(self.buses_tab, _fromUtf8(""))
        self.motors_tab = QtGui.QWidget()
        self.motors_tab.setObjectName(_fromUtf8("motors_tab"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.motors_tab)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.motors_webView = QtWebKit.QWebView(self.motors_tab)
        self.motors_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.motors_webView.setObjectName(_fromUtf8("motors_webView"))
        self.horizontalLayout_11.addWidget(self.motors_webView)
        self.configurations_tabs.addTab(self.motors_tab, _fromUtf8(""))
        self.alternativeFuels_tab = QtGui.QWidget()
        self.alternativeFuels_tab.setObjectName(_fromUtf8("alternativeFuels_tab"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.alternativeFuels_tab)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.alternativeFuels_webView = QtWebKit.QWebView(self.alternativeFuels_tab)
        self.alternativeFuels_webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.alternativeFuels_webView.setObjectName(_fromUtf8("alternativeFuels_webView"))
        self.horizontalLayout_12.addWidget(self.alternativeFuels_webView)
        self.configurations_tabs.addTab(self.alternativeFuels_tab, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.configurations_tabs)
        self.horizontalLayout_6.setStretch(2, 1)
        self.tabWidget.addTab(self.configuration_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        qtraffic_dockWidget.setWidget(self.qtraffic_widget)

        self.retranslateUi(qtraffic_dockWidget)
        self.tabWidget.setCurrentIndex(2)
        self.configurations_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(qtraffic_dockWidget)

    def retranslateUi(self, qtraffic_dockWidget):
        qtraffic_dockWidget.setWindowTitle(_translate("qtraffic_dockWidget", "QTraffic", None))
        self.groupBox.setTitle(_translate("qtraffic_dockWidget", "Input File", None))
        self.toolButton.setText(_translate("qtraffic_dockWidget", "...", None))
        self.groupBox_2.setTitle(_translate("qtraffic_dockWidget", "Table Column Select", None))
        self.label.setText(_translate("qtraffic_dockWidget", "Link ID", None))
        self.label_3.setText(_translate("qtraffic_dockWidget", "Veihcle Count", None))
        self.label_2.setText(_translate("qtraffic_dockWidget", "Link Type", None))
        self.label_4.setText(_translate("qtraffic_dockWidget", "Vehicle Speed", None))
        self.label_5.setText(_translate("qtraffic_dockWidget", "Road Lenght", None))
        self.label_6.setText(_translate("qtraffic_dockWidget", "Road Gradient", None))
        self.next_pushButton.setText(_translate("qtraffic_dockWidget", "Next ->", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_tab), _translate("qtraffic_dockWidget", "Input Network", None))
        self.groupBox_3.setTitle(_translate("qtraffic_dockWidget", "Output File", None))
        self.toolButton_2.setText(_translate("qtraffic_dockWidget", "...", None))
        self.comboBox.setItemText(0, _translate("qtraffic_dockWidget", "Emission factor times road lenght (g)", None))
        self.comboBox.setItemText(1, _translate("qtraffic_dockWidget", "Emission factor for each road segments (g/km)", None))
        self.groupBox_4.setTitle(_translate("qtraffic_dockWidget", "Pollutants", None))
        self.checkBox_6.setText(_translate("qtraffic_dockWidget", "SO2", None))
        self.checkBox_2.setText(_translate("qtraffic_dockWidget", "CO2", None))
        self.checkBox_3.setText(_translate("qtraffic_dockWidget", "NOx", None))
        self.checkBox_7.setText(_translate("qtraffic_dockWidget", "VOC", None))
        self.checkBox_4.setText(_translate("qtraffic_dockWidget", "Fuel Consumption", None))
        self.checkBox.setText(_translate("qtraffic_dockWidget", "CO", None))
        self.checkBox_5.setText(_translate("qtraffic_dockWidget", "PM", None))
        self.calculate_pushButton.setText(_translate("qtraffic_dockWidget", "Calculate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), _translate("qtraffic_dockWidget", "Output", None))
        self.newRoadType_button.setText(_translate("qtraffic_dockWidget", "New", None))
        self.removeRoadType_button.setText(_translate("qtraffic_dockWidget", "Remove", None))
        self.loadConfiguration_button.setText(_translate("qtraffic_dockWidget", "Load", None))
        self.saveConfiguration_button.setText(_translate("qtraffic_dockWidget", "Save", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.passengerCars_tab), _translate("qtraffic_dockWidget", "Passenger Cars", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.lightDutyVehicles_tab), _translate("qtraffic_dockWidget", "Light Duty Vehicles", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.heavyDutyVehicles_tab), _translate("qtraffic_dockWidget", "Heavy Duty Vehicles", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.buses_tab), _translate("qtraffic_dockWidget", "Buses", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.motors_tab), _translate("qtraffic_dockWidget", "Motors", None))
        self.configurations_tabs.setTabText(self.configurations_tabs.indexOf(self.alternativeFuels_tab), _translate("qtraffic_dockWidget", "Alternative Fuels", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration_tab), _translate("qtraffic_dockWidget", "Configuration", None))

from PyQt4 import QtWebKit
